
@Layout = require("./layout")

@Home = require("./pages/home")
@Writing = require("./pages/writing")
@WritingView = require("./pages/writingView")
@Photography = require("./pages/photography")
@PhotographyView = require("./pages/photographyView")
@Ideas = require("./pages/ideas")
@Tags = require("./pages/tags")
@Settings = require("./pages/settings")
@New = require("./pages/new")
@Edit = require("./pages/edit")
@Login = require("./pages/login")
@Logout = require("./pages/logout")
@NotFound = require("./pages/notFound")