@date = require("./date")
@imageUpload = require('./imageUpload')
@selectLabels = require("./selectLabels")
@text = require("./text")
@validators = require("./validators")
@mixin = require("./mixin")
@form = require("./form")